### ISSUE TITLE
Crypto-Currency Exchange Dapp [ uniswap 2.0 ] 

### ISSUE THREAD

**Issue by Sanitya7** [Vikash-8090-Yadav/Future.WebNet#157]
### Project title
Build and Deploy a Web 3.0 Cryptocurrency Exchange Decentralized Application

### Project Description
a decentralized cryptocurrency exchange React application with metamask pairing, live smart contract data fetching, and most importantly, the ability to create your own ERC20 tokens, swap them and more!

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSOC'23 
<hr/>

**Comment by Sanitya7** [comment]
Thanks @Vikash-8090-Yadav , 
Sure, shall add it in level 2. 👌

**Comment by Vikash-8090-Yadav** [comment]
Hey @Sanitya7 are u still  working on this ?
