### ISSUE TITLE
NFT Marketplace

### ISSUE THREAD

**Issue by Syedhussainsaber** [Vikash-8090-Yadav/Future.WebNet#159]
### Project Description
Decentralised NFT Marketplace is an online decentralised platform to buy, sell or list a NFT. This is a complete Full Stack Blockchain Application created on Ethereum Blockchain Network.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [x] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes

<hr/>

**Comment by Syedhussainsaber** [comment]
Hi can you assign me this project, I am already started working on this

**Comment by Vikash-8090-Yadav** [comment]
There's already a NFT MARKETPLACE project present .How's ur diffrent from that !

**Comment by Syedhussainsaber** [comment]
It based on Ethereum blockchain with more features such as event notifying for listing and selling the nft, modern ui,p2p transactions of the nft. Techs using in this project are solidity, ethers js, hardhat, next js, moralis and also graphs.

**Comment by Vikash-8090-Yadav** [comment]
> It based on Ethereum blockchain with more features such as event notifying for listing and selling the nft, modern ui,p2p transactions of the nft. Techs using in this project are solidity, ethers js, hardhat, next js, moralis and also graphs.

Gr8 .Start working on this .

**Comment by Syedhussainsaber** [comment]
Thanks 🤗

**Comment by Eren-Yeaager** [comment]
Hi, Can I contribute to this project?

**Comment by Kali-Decoder** [comment]
how can we contribute to projects
