### ISSUE TITLE
Website for showcasing NFTs

### ISSUE THREAD

**Issue by monishkajha17** [Vikash-8090-Yadav/Future.WebNet#174]
### Description of  the change
Describe more about the change.

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great start working on  this

**Comment by Abhinavcode13** [comment]
Can I work on this issue?

**Comment by Vikash-8090-Yadav** [comment]
Are you  a contributor from SSOC ?

**Comment by Vikash-8090-Yadav** [comment]
@monishkajha17 are u still working on this ??

**Comment by Abhinavcode13** [comment]
Yes I'm contributor from SS0C 2.0

**Comment by Vikash-8090-Yadav** [comment]
> Yes I'm contributor from SS0C 2.0

> @Vikash-8090-Yadav is it still open can i work on this

Don't forget to introduce yourself in the community discussion  https://github.com/Vikash-8090-Yadav/Future.WebNet/discussions/146
