### ISSUE TITLE
Blog on Proof of Stake 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Future.WebNet#179]
Hey everyone , Ethereum switched on its proof-of-stake mechanism in 2022 because it is more secure, less energy-intensive, .......contnue .

Goal :
Write about the Polygon Blockchain , it's use cases and if possible explain this with the help of the images .

Pattern 
<ul>
<li>
 Introduction (with images )
</li>
  <li>Full  fledge explation of the topn with images (Preffer to write in points)
</li> 
</ul>
<br>
Refrence :

 https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/

**Comment by nerdy-nakul** [comment]
Hello @Vikash-8090-Yadav,
I'm a IWOC participant, can i work on this issue?

**Comment by Vikash-8090-Yadav** [comment]
Ys surr , for the blog guidelines u can see the .merged one , and don't forget to introduce yourself to community ! 

https://github.com/Vikash-8090-Yadav/Web3.0-World/discussions/146

**Comment by nerdy-nakul** [comment]
> Ys sure , for the blog guidelines u can see the .merged one , and don't forget to introduce yourself to community !
> 
> #146

Okay.

**Comment by chikkibum** [comment]
@Vikash-8090-Yadav is the issue being worked upon?

**Comment by nerdy-nakul** [comment]
> @Vikash-8090-Yadav is the issue being worked upon?

Yes, my blog on proof of stake is under progress.

**Comment by chikkibum** [comment]
@nerdy-nakul ok carry on

**Comment by Abhinavcode13** [comment]
Is this issue resolved? @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
@Abhinavcode13  if u participating under the SSOC. Then wait for the open ceremony.  Before that your contribution would not  be counted.

**Comment by 0xSaksham** [comment]
@Vikash-8090-Yadav I want to write the blog.

I am fro SSOC

**Comment by SomilRathore01** [comment]
Hey! @Vikash-8090-Yadav, I would like to resolve this project, as I am competing in SSOC'23. I will write the blog with great front-end design in it. Please assign this project to me.

**Comment by Parthmandale** [comment]
@Vikash-8090-Yadav I can work on this issue, and write an outstanding blog, similar to Ethereum killers blog!

**Comment by praAddy** [comment]
Hello, @Vikash-8090-Yadav I'm interested in working on this issue.

**Comment by Vikash-8090-Yadav** [comment]
> can i work on this issue, please assign me
> 

Already assigned bro

**Comment by NupurHardiya** [comment]
Hello @Vikash-8090-Yadav,
I would be grateful if you could assign me the opportunity to contribute to this issue under SSOC'23 , as I am eager to cover the topics of Proof of Stake and the Polygon Blockchain, sharing valuable insights and sparking engaging discussions within the community. Thank you for considering my request.

**Comment by 0xSaksham** [comment]
Hi Everyone, sorry for the delay. I'll start working on this ASAP.

**Comment by 0xSaksham** [comment]
> Ys sure , for the blog guidelines u can see the .merged one , and don't forget to introduce yourself to community !
> 
> #146

Where's the merged one?
