### ISSUE TITLE
Improve the UI of the level0 projects

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Future.WebNet#2]
Improve the frontend part of the level0 projects .

**Comment by ankur0904** [comment]
I want work on the frontend part. Please assign it to me.

**Comment by Vikash-8090-Yadav** [comment]
@ankur0904  your task is to improve the frontend part of the level0 project and please tell the name of the project u wana to improve..

**Comment by kunal232i** [comment]
I want to work on this issue (on level0->Login_page) can you assign this for me..?

**Comment by Vikash-8090-Yadav** [comment]
> 

Raise a seperate issue for this ... @kunal232i

**Comment by Vikash-8090-Yadav** [comment]
> @ankur0904 your task is to improve the frontend part of the level0 project and please tell the name of the project u wana to improve..

@kunal232i  ??

**Comment by ankur0904** [comment]
okay sir

**Comment by Vikash-8090-Yadav** [comment]
> okay sir

please tell the file name in which u want to contribute ?

**Comment by kunal232i** [comment]
> I want to work on this issue (on level0->Login_page) can you assign this for me..?

sure 👍

**Comment by Vikash-8090-Yadav** [comment]
@kunal232i  on which project u r working ?

**Comment by ankur0904** [comment]
Web3.0-World->Level0->Mood

**Comment by Vikash-8090-Yadav** [comment]
ok @kunal232i  Start working on this ...

**Comment by iamifechi** [comment]
I want to work on this >> Web3.0-World/Level0/SendToEather/

**Comment by Vikash-8090-Yadav** [comment]
> I want to work on this >> Web3.0-World/Level0/SendToEather/

ok ...Make a new Issue for this ...

**Comment by kunal232i** [comment]
> ok @kunal232i Start working on this ...
I amd done with my work of Login page.

**Comment by SomeshShinde24** [comment]
Please assign this issue to me

**Comment by Vikash-8090-Yadav** [comment]
Sure @SomeshShinde24 . Start working on this .

**Comment by Bharadwajshivam28** [comment]
@Vikash-8090-Yadav  Is it done sir if not then please assign to me

**Comment by SomilRathore01** [comment]
Hey! @Vikash-8090-Yadav, I would like contribute in project, please assign it to me for competing in SSOC'23. I will enhance the UI of this project.

**Comment by Parthmandale** [comment]
Thanks for Reopening the issue @Vikash-8090-Yadav , I've good ideas to improve the UI please assign this to me!

**Comment by Vikash-8090-Yadav** [comment]
Wait for 1st june.

**Comment by Vikash-8090-Yadav** [comment]
Wait for 1st june.

**Comment by harshit-sharmaaa** [comment]
I want to work on improvement of this UI , please assign this to me @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
> I want to work on improvement of this UI , please assign this to me @Vikash-8090-Yadav 

Create anew issue for this*

**Comment by TanishqSiva** [comment]
I'm intrested to work on this issue, please assign it to me!

**Comment by Vikash-8090-Yadav** [comment]
which project under level0 u wana improve??

**Comment by Parthmandale** [comment]
Sure, you can do this to me, I will improve it!!
please assign this to me @Vikash-8090-Yadav

**Comment by shrutimishra27** [comment]
Hey @Vikash-8090-Yadav , an SSOC'23 contributor here.
I would like to improve the UI of SendToEther of Level0 project if you assign it to me.

**Comment by harshit-sharmaaa** [comment]
Hey @Vikash-8090-Yadav , an SSOC'23 contributor here.
I would like to improve the UI of Mood of Level0 project if you assign it to me.
![Screenshot_20230605_102751](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/121124691/146f0061-7e87-436f-ac5a-70888370e035)

**Comment by Vikash-8090-Yadav** [comment]
> Sure, you can do this to me, I will improve it!!
> please assign this to me @Vikash-8090-Yadav 

Raise an issue for this.

**Comment by Vikash-8090-Yadav** [comment]
> Hey @Vikash-8090-Yadav , an SSOC'23 contributor here.
> I would like to improve the UI of SendToEther of Level0 project if you assign it to me.

Raise an issue for this.

**Comment by Vikash-8090-Yadav** [comment]
> Hey @Vikash-8090-Yadav , an SSOC'23 contributor here.
> I would like to improve the UI of Mood of Level0 project if you assign it to me.
> ![Screenshot_20230605_102751](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/121124691/146f0061-7e87-436f-ac5a-70888370e035)
> 

Raise an issue for this.

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav I would like to improve the UI of level 0 project. Please assign it to me.
