### ISSUE TITLE
Blockchain Chat App

### ISSUE THREAD

**Issue by Nidhish-07** [Vikash-8090-Yadav/Future.WebNet#205]
### Project title
Blockchain Chat App

### Project Description
A blockchain based chat app where you can register yourself and chat with different people.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

Yes
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
ya sure ,  include this in level2 .

**Comment by KunalSiyag** [comment]
Hello sir,
I am Kunal Siyag (I want to start my journey in open source as well as web3 with this project).
Github-profile: https://github.com/kunalsiyag
Email-Id: kunalsiyag829@gmail.com
kindly assign this issue to me.
