### ISSUE TITLE
Metaverse project 1

### ISSUE THREAD

**Issue by daredevil3435** [Vikash-8090-Yadav/Future.WebNet#208]
### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

Yes. SWOC 3.0

**Comment by daredevil3435** [comment]
@Vikash-8090-Yadav sir check this issue and assign in to me.

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav sir check this issue and assign in to me.

Start working on this .

**Comment by Vikash-8090-Yadav** [comment]
@daredevil3435 are u still working on this ??

**Comment by daredevil3435** [comment]
> @daredevil3435 are u still working on this ??
> 
> 

Yes. I'll submit by tomorrow

**Comment by akshaya-hub** [comment]
@Vikash-8090-Yadav  is it still open can i work on this

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav is it still open can i work on this

Yup . but if u are from ssoc then wait for the open ceremony . All the issue which are opened are active . But don't forget to introduce yourself in the community discussion  https://github.com/Vikash-8090-Yadav/Future.WebNet/discussions/146

**Comment by 0xSaksham** [comment]
@Vikash-8090-Yadav I want to work on this.

I am fro ssoc.
