### ISSUE TITLE
Tesla Clone

### ISSUE THREAD

**Issue by Nidhish-07** [Vikash-8090-Yadav/Future.WebNet#214]
### Project title
Tesla Clone

### Project Description
A Tesla Website clone using ReactJs and tailwind CSS

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Gr8  , but this in the Frontend directory !!
