### ISSUE TITLE
Weaving Craft Supply Chain (WeaveChain Dapp)

### ISSUE THREAD

**Issue by Raguna9** [Vikash-8090-Yadav/Future.WebNet#220]
### Project title
Decentralize Weaving Craft Supply Chain

### Project Description
WeaveChain is an application for managing the supply chain of handwoven crafts (traditional fabric-making by SMEs in Indonesia) using the Ethereum blockchain. Within the application, users can register as actors and perform transactions such as asset processing, buying and selling assets, and tracking assets from upstream to downstream.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
No
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Thanks for opening this issue. Push this in level2 directory with the good readme and video.

**Comment by Raguna9** [comment]
thanks @Vikash-8090-Yadav , i'll add it quickly
