### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [Vikash-8090-Yadav/Future.WebNet#222]
I would like to work on improving the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under SSoC'23.

**Comment by Mallika-2002** [comment]
I would like to work on this issue under SSOC'23 .Kindly assign to me.

**Comment by Parthmandale** [comment]
I would like to work on this issue @Vikash-8090-Yadav ser

**Comment by VedantDomadiya** [comment]
I would like to work on this issue under SSOC'23. kindly assign me to start working on it

**Comment by NupurHardiya** [comment]
I would like to work on this issue _@Vikash-8090-Yadav_ sir under **SSOC'23**.  kindly assign me to start working on it

**Comment by TMTanmay1** [comment]
I would like to work on this issue @Vikash-8090-Yadav sir..
Please assign it to me.

**Comment by Vikash-8090-Yadav** [comment]
Hey bro as said in the meet you are not supposed just comment on this, about your idea of what u wanna improve in the readme so that i can assign you. Thanks!

**Comment by weedertree** [comment]
sir i<d like to contribute pls assign me the project
