### ISSUE TITLE
Add more  project  idea

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Future.WebNet#224]
Hey if anyone wants to start  with the documentation part then please do comment.

**Comment by vaibhav4gaur** [comment]
yes i am also be part to starting in documentation..

**Comment by Ananya01Agrawal** [comment]
Yes, I can start with documentation, assign this to me

**Comment by Vikash-8090-Yadav** [comment]
Hey those who are intersted please raise an issue along with your proposed idea. Thanks!!
