### ISSUE TITLE
Make your own issue SSOC

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Future.WebNet#225]
Please comment about your ideas and project so that I can make an issue for you and assigned it. https://github.com/Vikash-8090-Yadav/Future.WebNet/issues/225

**Comment by harshit-sharmaaa** [comment]
i want to improve level0 Mood UI under SSOC'23
![image](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/121124691/1b3b63ef-7cdf-4d3a-b230-96349244a08c)
