### ISSUE TITLE
To do app

### ISSUE THREAD

**Issue by VardaPanchal005** [Vikash-8090-Yadav/Future.WebNet#226]
Blockchain to do app with Etherium smart contracts  using the Solidity programming language.
Please assign this issue to me
@Vikash-8090-Yadav

**Comment by Manish12-verma** [comment]
hey please assign this issue to me

**Comment by VardaPanchal005** [comment]
> hey please assign this issue to me

This project is assigned to me you can create a new issue

**Comment by shubhisingh184** [comment]
@VardaPanchal005 Are you working on this issue?

**Comment by VardaPanchal005** [comment]
Yes its almost done

> @VardaPanchal005 Are you working on this issue?

**Comment by shubhisingh184** [comment]
> Yes its almost done
> 
> > @VardaPanchal005 Are you working on this issue?

Great!
