### ISSUE TITLE
Improve UI for level 0

### ISSUE THREAD

**Issue by harshit-sharmaaa** [Vikash-8090-Yadav/Future.WebNet#228]
### Description of  the change
Describe more about the change.

### Domain of Docs

- [] Readme
- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Hey bro, which project under level0 u wana to improve?

**Comment by TanishqSiva** [comment]
I want to do the 2nd one which "Solidity , Html, Css , JavaScript , Web3.js / Ether.js", Can u assign it to me

**Comment by harshit-sharmaaa** [comment]
I want to improve Voting Project 
![Screenshot_20230601_221317](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/121124691/a55f1066-27de-4338-a4b4-f2d6e9ba7172)

**Comment by Vikash-8090-Yadav** [comment]
Raise issue for this

**Comment by Shu12388y** [comment]
@Vikash-8090-Yadav I want to improve the UI of the login_page of level 0 folder can you assign the issue to me
