### ISSUE TITLE
improve  the intro of blockchain..

### ISSUE THREAD

**Issue by vaibhav4gaur** [Vikash-8090-Yadav/Future.WebNet#229]
![Screenshot 2023-06-01 at 11 38 20 PM](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/110227490/606bfc11-0ade-4459-8046-34d6485d9eb5)
There is a problem in the lines of readme file. I  am fix this issue, so you can assign me this file...

**Comment by Vikash-8090-Yadav** [comment]
Can u please describe the problem.

**Comment by vaibhav4gaur** [comment]
ViKASH SIR, i am add references links  and add lines in conclusion..

**Comment by Vikash-8090-Yadav** [comment]
Gr8.

**Comment by vaibhav4gaur** [comment]
sir add the ssoc 2.0 label
