### ISSUE TITLE
Improve UI of Voting Project under level 0

### ISSUE THREAD

**Issue by harshit-sharmaaa** [Vikash-8090-Yadav/Future.WebNet#230]
### Description of  the change
Describe more about the change.

### Domain of Docs

- [] Readme
- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Which project u want to improve  under level 0?

**Comment by harshit-sharmaaa** [comment]
Voting Project
![Screenshot_20230601_221317](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/121124691/956b1b51-b7e7-40c2-a5fe-5c7b73955968)

**Comment by harshit-sharmaaa** [comment]
I am a SSOC contributer

**Comment by Vikash-8090-Yadav** [comment]
Great start working on  this
