### ISSUE TITLE
Create recipe book web application

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#233]
### Project title
(Write project title over here)

### Project Description
(Describe the project over here)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this.

**Comment by Tusharjoshi1703** [comment]
Thank you for assigning it to me . I will make sure that I will give my
best to it.
