### ISSUE TITLE
Add new Weather App

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#234]
### Project title
(Write project title over here)

### Project Description
(Describe the project over here)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this

**Comment by Tusharjoshi1703** [comment]
Thank you for assigning it to me.

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav Please assign me this
