### ISSUE TITLE
Zomato landing page clone by Html & Css

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#235]
### Project title
(Write project title over here)

### Project Description
(Describe the project over here)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by TanishqPal-tech** [comment]
I am a contributor at SSOC I want to contribute in this issue please assign me as this a perfect to my skill

**Comment by TanishqPal-tech** [comment]
I am a contributor at SSOC I want to contribute in this issue please assign me as this a perfect to my skill

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this

**Comment by Tusharjoshi1703** [comment]
Thank you for assigning it to me.

**Comment by TanishqSiva** [comment]
I'm from SSOC, I'm have enough good experience in making landing pages, Can you please assign it to me @Vikash-8090-Yadav

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav I'm a contributer with SSOC , Please assign me this
