### ISSUE TITLE
2048 Game using HTML CSS JS

### ISSUE THREAD

**Issue by MohamedMafaz** [Vikash-8090-Yadav/Future.WebNet#236]
### Project title
2048 Game

- [] Solidity , Html, Css , JavaScript

#### Are you contributing under any open-source program ?
SSOC'23
<hr/>

**Comment by NupurHardiya** [comment]
Dear SSOC'23 organizers @Vikash-8090-Yadav, I kindly request to be assigned the task of developing a thrilling car racing game using HTML, CSS, and JavaScript, as my contribution towards the event.

**Comment by Vikash-8090-Yadav** [comment]
> Dear SSOC'23 organizers @Vikash-8090-Yadav, I kindly request to be assigned the task of developing a thrilling car racing game using HTML, CSS, and JavaScript, as my contribution towards the event.

Raise an issue for this.

**Comment by Vikash-8090-Yadav** [comment]
@MohamedMafaz start working on this,

**Comment by shubhisingh184** [comment]
@MohamedMafaz Are you working on this issue?

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 sir, please assign this project to me
