### ISSUE TITLE
book store app

### ISSUE THREAD

**Issue by rajputsingh808** [Vikash-8090-Yadav/Future.WebNet#238]
### Project title
e-book website

### Project Description

it's a e-book website having different feature and totally responsive

### Doc Domain
- [] Solidity , Html, Css , JavaScript , 
- [] Other , feel free to mention below

**Comment by Vikash-8090-Yadav** [comment]
Great start workig on this.

**Comment by shubhisingh184** [comment]
@rajputsingh808 Are you working on this issue?

**Comment by rajputsingh808** [comment]
yes ,sir
almost done with this
