### ISSUE TITLE
Improve the UI and add content for the "Codeclub" project 

### ISSUE THREAD

**Issue by Aryaman3007** [Vikash-8090-Yadav/Future.WebNet#240]
### Description of  the change
Improve the user interface by adding some features and add content in the website to help the users.
### Domain of Docs

- [x] Html, Css , JavaScript 

#### Are you contributing under any open-source program ?
SSoC 2023 

<hr/>Kindly assign me this issue @Vikash-8090-Yadav .

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this.

**Comment by Aryaman3007** [comment]
I have a doubt , can I make this project with react or I have to work with the given files.

**Comment by Vikash-8090-Yadav** [comment]
> I have a doubt , can I make this project with react or I have to work with the given files.

You can make this with react as well. Raise an issue to improve the issue template. Thanks

**Comment by Aryaman3007** [comment]
This issue is not shown on quine, so should I wait or start it.

**Comment by Vikash-8090-Yadav** [comment]
> This issue is not shown on quine, so should I wait or start it. 

No worries, start working.
