### ISSUE TITLE
To add Google Clone 

### ISSUE THREAD

**Issue by ayan-joshi** [Vikash-8090-Yadav/Future.WebNet#241]
### Project title
Google clone is a simple frontend project with html and css

### Project Description
Google clone will made for three pages like the google interface then google images and the advanced search page as well.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
I am a SSOC contributor please assign me this issue @Vikash-8090-Yadav 
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this.

**Comment by ayan-joshi** [comment]
lesgooo thanks
