### ISSUE TITLE
Join  this channel [SSOC FUTURE.WEBNET] 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Future.WebNet#242]
Hey if anyone is still not added to this channel and contributing under ssoc then please do Join.
Join the below server/ channel.

[Future.webNet Channel](https://discord.com/channels/1090517489445785650/1112453967616675970)

**Comment by Daksh-Maru** [comment]
Please assign this task to me.

**Comment by Vikash-8090-Yadav** [comment]
This issue is not for the Contributor.
