### ISSUE TITLE
Inconsistencies in 'Cricket'

### ISSUE THREAD

**Issue by bugzzz4u** [Vikash-8090-Yadav/Future.WebNet#247]
<img width="960" alt="Screenshot 2023-06-04 01 07 04" src="https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/125059410/6d950e4a-9a44-4ec4-9372-41da790cea75">

Problems :
1.  Poor UI Interface: The look is not appealing and attractive.
2. Bad Color Theme: The color chosen is not at all tempting.
3. Font family and color issue: Alter font to make the site look better.
4. Better layout and sectioning

There is a need to change the whole design of this website.

**Comment by Shu12388y** [comment]
@bugzzz4u  can you assign this issue to me

**Comment by Zaid1681** [comment]
@bugzzz4u assign me this issue , I am happy to make the changes and improve the UI
