### ISSUE TITLE
Buy Me a Coffee

### ISSUE THREAD

**Issue by Shu12388y** [Vikash-8090-Yadav/Future.WebNet#249]
![buy me a coffee](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/695c7313-491d-4014-acef-3e343c4e987c)

<h1>
Clone of Buy Me a Coffee
</h1>

<h2>
Project suggestion for SSOC'23 for frontend project
</h2>

@Vikash-8090-Yadav  can you assign this project to me

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this. Thanks!
