### ISSUE TITLE
To add Tesla Homepage Clone

### ISSUE THREAD

**Issue by SPARSH1608** [Vikash-8090-Yadav/Future.WebNet#254]
### **Project title**
Tesla Homepage clone will be made using react and redux.

**### Project Description**
Tesla Homepage clone will be made using react styled components , MUI and hooks.

**### Doc Domain**
[] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
[] Solidity , ReactJs /NextJs , Web3.js /Ether.js
[] Solidity , Python3 , Web3.py
[] Other , feel free to mention below

Are you contributing under any open-source program ?

I am a SSOC contributor please assign me this issue @Vikash-8090-Yadav

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 sir, please assign this task to me for contribution under SSoC 2.0
