### ISSUE TITLE
To add Google Drive Clone

### ISSUE THREAD

**Issue by SPARSH1608** [Vikash-8090-Yadav/Future.WebNet#255]
Project title
Google drive Clone is made using react , redux toolkit and firebase.

### Project Description
Google drive which is very popular for storing images , pdf and images will be cloned using react , redux toolkit and firebase.

### Doc Domain
[] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
[] Solidity , ReactJs /NextJs , Web3.js /Ether.js
[] Solidity , Python3 , Web3.py
[] Other , feel free to mention below

Are you contributing under any open-source program ?

I am a SSOC contributor please assign me this issue @Vikash-8090-Yadav

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 sir, can you please assign it to me
