### ISSUE TITLE
Improve The UI of Log_In page of Level 0

### ISSUE THREAD

**Issue by Shu12388y** [Vikash-8090-Yadav/Future.WebNet#257]
### Description of  the change
Describe more about the change.

![Screenshot (3)](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/2113a10a-85b4-41bf-8724-659d2ea99f16)

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

@Vikash-8090-Yadav  can you assign this issue to me. I want to improve the UI of the Log_In page under SSOC'23
<hr/>

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav Please assugn this to me
