### ISSUE TITLE
Real Estate Email html template

### ISSUE THREAD

**Issue by Shu12388y** [Vikash-8090-Yadav/Future.WebNet#260]
### Project title
Real Estate Email HTML template

![html_email_template](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/47d7a982-176f-4d7c-8fdd-d6f13c63122e)

### Project Description
Email HTML template which we can use in Gmail also

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

@Vikash-8090-Yadav  can you assign this project to me 
<hr/>

**Comment by TanishqSiva** [comment]
@Vikash-8090-Yadav I'm intrested to work on it, Can you please assign it to me.
