### ISSUE TITLE
3D parallax website using HTML CSS and JavaScript

### ISSUE THREAD

**Issue by Romit77** [Vikash-8090-Yadav/Future.WebNet#262]
### Project title
3D parallax website using HTML CSS and JavaScript

### Project Description
A webiste which uses Javascript to create a 3D parallax effect.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
SSoC'23

<hr/>

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav Please assign me this project.
