### ISSUE TITLE
NFT sharing dApp

### ISSUE THREAD

**Issue by AyushPathak3011** [Vikash-8090-Yadav/Future.WebNet#27]
### Project title
NFT sharing dApp

### Project Description
A Social Media dApp, similar to Instagram, is a decentralized version of the Instagram platform for pets where users can browse photos of their favorite pets, see details of a specific pet, create a post and earn NFTs.

### Doc Domain

- [x] Solidity , ReactJs /NextJs , Web3.js /Ether.js, IPFS

#### Are you contributing under any open-source program?
SSOC '22
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great idea @AyushPathak3011  can u please tell the folder structure in which u wana to add this .

**Comment by AyushPathak3011** [comment]
> Great idea @AyushPathak3011 can u please tell the folder structure in which u wana to add this .

Web3.0-World/Level2/NFT-Sharing-dApp

**Comment by Vikash-8090-Yadav** [comment]
> > Great idea @AyushPathak3011 can u please tell the folder structure in which u wana to add this .
> 
> Web3.0-World/Level2/NFT-Sharing-dApp

Fine .. start working on this

**Comment by legendarykamal** [comment]
HI @AyushPathak3011 since this seems to be a long project , would you mind working on this together? 

// @Vikash-8090-Yadav is that possible?

**Comment by Vikash-8090-Yadav** [comment]
If u  are talking  under the SSOC'22 then not possible cux this is open source programme individual contribution matters.

**Comment by Vikash-8090-Yadav** [comment]
@AyushPathak3011 any updates ?

**Comment by AyushPathak3011** [comment]
> @AyushPathak3011 any updates ?

Sorry for being inactive, had some personal commitments.
Yes I am working on the final stages of this project, will update soon.

**Comment by Vikash-8090-Yadav** [comment]
@AyushPathak3011  . Any updates ???

**Comment by Vikash-8090-Yadav** [comment]
@AyushPathak3011 areu still working on this ?
