### ISSUE TITLE
[Docs] Workflow for updating dependencies

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Vikash-8090-Yadav/Future.WebNet#270]
Workflow to update dependencies: This workflow will handle updating dependencies as demonstrated in the image provided.

![image](https://user-images.githubusercontent.com/74038190/243422997-69ba6152-51a7-4c2e-8975-5c2af7cc0c89.png)

> If this workflow is relevant to the repository, let me know.

Please assign me, and I will start contributing to this issue by creating a pull request. 

I would like to contribute to this under SSOC'23.

**Comment by Vikash-8090-Yadav** [comment]
Nope not required, this is not the single project repo. Thanks!
