### ISSUE TITLE
Improve the UI and functionality of Voting Project of Level0

### ISSUE THREAD

**Issue by shrutimishra27** [Vikash-8090-Yadav/Future.WebNet#277]
UI + Functionality Improvement List:
 - [ ] Navbar for homepage
 - [ ] Animations
 - [ ] Responsiveness
 - [ ] Color Combinations 
 - [ ] Winner announcement page after clicking Check Result Button
 
 Original Project UI:
 ![image](https://user-images.githubusercontent.com/85816852/181049228-c8dd2b9e-9f37-4466-aa03-9cbc898ca627.png)

**Comment by Vikash-8090-Yadav** [comment]
Nope, Raise  the issue for the other voting project available. Thanks!
