### ISSUE TITLE
[SSoC'23 2.0] Improving the Main Readme file

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#280]
### Description of  the change
- Improving the comments
- Improving the code line for cloning
As `git clone https://github.com/<your-github-username>/Web3.0-World`, 
this code line should be `git clone https://github.com/<your-github-username>/Future.WebNet`.

- Also updating other code lines for easy use for users who wants to contribute.

### Domain of Docs

- [x] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC'23 2.0
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Please /assign this issue to me to contribute under SSoC'23 2.0 program.

**Comment by Avdhesh-Varshney** [comment]
Sir @Vikash-8090-Yadav 
- I will update the heading line or not ? 
- Line 3 of main readme file : `# <p align = "center"> Web3.O.World </p>`
- Heading - **Web3.O.World** to **Future WEB-NET**
- Also in other readme files ? (like read me files of level 0, level 1, level 2, etc.)

And sir please add the **level-3** label to the bingo game issue #265 as i am adding many features to that game like adding background music, go for multi players, adding sounds controls, adding sound of cross, and congrats page with cool sound and animation, etc.

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir please response

**Comment by Vikash-8090-Yadav** [comment]
except the heading that is Web3-World do all the parts.
