### ISSUE TITLE
Improve the UI and functionality of New_Voting Project of Level0

### ISSUE THREAD

**Issue by shrutimishra27** [Vikash-8090-Yadav/Future.WebNet#281]
UI + Functionality Improvement List:
 - [ ] Major CSS structuring
 - [ ] Responsiveness
 - [ ] Color Combinations 
 - [ ] Functionality for Vote button -> Counter in JavaScript
 - [ ] Winner announcement page after clicking Check Result Button
 - [ ]  Animations(just a few to add)

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this.

**Comment by shrutimishra27** [comment]
Hey @Vikash-8090-Yadav, right now I am done with top 3 tasks of this issue i.e. the UI.
Should I give a merge request till that part to you so that it would be easier for you to review and test changes until that?
Then I will continue my other 3 tasks i.e. the Functionality.
This will be better for both of us I guess. Else you suggest.

**Comment by shrutimishra27** [comment]
Hey @Vikash-8090-Yadav, I have completed this [#issue281](https://github.com/Vikash-8090-Yadav/Future.WebNet/pull/290)

### Update: Not a single line of code is removed from index.html and index.js files.
