### ISSUE TITLE
To improve champions page of project cricket

### ISSUE THREAD

**Issue by ayan-joshi** [Vikash-8090-Yadav/Future.WebNet#282]
### Description of  the change
The champs.html file in the cricket have many problems , it should show the champions in 2000-2021 but it's not opening and the data present in the champs.html is same as the records.html so it will not show the champions anyway so I want to update it to show the champions file properly.

![Screenshot (178)](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/96243602/b6a78c14-5ba9-4e1d-bea0-aa95de74c3b5)

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
I am a SSOC contributor @Vikash-8090-Yadav please assign me this issue 
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on  this.
