### ISSUE TITLE
To add Myntra Clone in front end projects 

### ISSUE THREAD

**Issue by ayan-joshi** [Vikash-8090-Yadav/Future.WebNet#283]
### Project title
I will add a myntra clone to the frontend projects folder

### Project Description
I will made a responsive introduction page of myntra as a clone.
I will use html, css, javascript so it will be a very nice project for the beignner in your repository.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
I'm a SSOC contributor @Vikash-8090-Yadav please assign me this issue.
<hr/>

**Comment by TanishqSiva** [comment]
I'm a SSOC contributor @Vikash-8090-Yadav please assign me this issue.

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on  this.

**Comment by TanishqSiva** [comment]
@ayan-joshi Lets connect one on one send me your linkedin to get in touch lets start working on it
