### ISSUE TITLE
New Frontend Project: Drum Game

### ISSUE THREAD

**Issue by shrutimishra27** [Vikash-8090-Yadav/Future.WebNet#286]
### Project title
Drum Kit

### Project Description
The Drum Kit game is a simple but fun game that allows you to play drums on your computer. The game is built using HTML, CSS, and JavaScript, and it is fully responsive, meaning that it works on all devices.

### Project Working
To play the game, simply press the keys on your keyboard to hit the drums. The different keys correspond to different drums, so you can create your own beats and rhythms.

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? SSOC'23

<hr/>

**Comment by shrutimishra27** [comment]
Hey @Vikash-8090-Yadav, it would be great if this project(Audio-based new type) is added in your repository.
Please assign if you like it.

**Comment by harshitaaa8** [comment]
Can i also try to work on this game @Vikash-8090-Yadav ??
looking for my first contribution in SSOC'23

**Comment by shrutimishra27** [comment]
@Vikash-8090-Yadav  I am almost done with making of this game.
Will create a merge request by today.
