### ISSUE TITLE
TASK MANAGER

### ISSUE THREAD

**Issue by NupurHardiya** [Vikash-8090-Yadav/Future.WebNet#287]
### Project title
(Write project title over here)

### Project Description
(Describe the project over here)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by NupurHardiya** [comment]
Dear SSOC'23 organizer @Vikash-8090-Yadav, I request to develop a captivating Task Manager web app using HTML, CSS, and JavaScript as my contribution. Excited to showcase my skills and deliver a valuable application for the event. Please assign it to me. Thank you for considering my request.

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on  this.
