### ISSUE TITLE
Spotify Clone

### ISSUE THREAD

**Issue by KrAman66** [Vikash-8090-Yadav/Future.WebNet#289]
Project title
I will add a Spotify clone to the frontend projects folder

Project Description
I will made a responsive introduction page of spotify as a clone.
I will use html, css, javascript so it will be a very nice project for the beignner in your repository.

Doc Domain
[] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
[] Solidity , ReactJs /NextJs , Web3.js /Ether.js
[] Solidity , Python3 , Web3.py
[] Other , feel free to mention below
Are you contributing under any open-source program ?
I'm a SSOC contributor @Vikash-8090-Yadav please assign me this issue.

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on  this.

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav Please assign me this project
