### ISSUE TITLE
Add a Payment Form Project 

### ISSUE THREAD

**Issue by Venerablevivek** [Vikash-8090-Yadav/Future.WebNet#291]
### Project title
Payment Form Using HTML5 and CSS3

### Project Description
Create a basic Payment form which includes taking important details of
the User. It has been implemented using HTML and CSS

### Doc Domain
https://venerablevivek.github.io/PaymentForm/

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yess, SSOC'23
<hr/>
![Screenshot (952)](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/81643632/4173c909-1264-4050-8240-089dff3368ad)
![Screenshot (953)](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/81643632/7cb8d2f8-1866-4783-b1e8-5bf2189a9c33)

**Comment by Venerablevivek** [comment]
@Vikash-8090-Yadav ... Please Assign this to me ... I want to contribute this

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on  this.

**Comment by Venerablevivek** [comment]
Yes, @Vikash-8090-Yadav in which Level folder to add ?

**Comment by Vikash-8090-Yadav** [comment]
> Yes, @Vikash-8090-Yadav in which Level folder to add ?

Add this  in Frontend directory

**Comment by Venerablevivek** [comment]
@Vikash-8090-Yadav I have successfully added it
can you check it
