### ISSUE TITLE
Code Pen Clone

### ISSUE THREAD

**Issue by Vidip-Ghosh** [Vikash-8090-Yadav/Future.WebNet#292]
### Project title
Code Pen Clone 

### Project Description
It is an online editor for HTML, CSS, JS Code. https://codepenwebsiteclone.netlify.app/
It is created using React JS + Material UI.
### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
I am contributing under SSOC 2.0
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this.
