### ISSUE TITLE
Youtube Clone under SSOC '23

### ISSUE THREAD

**Issue by harshit-sharmaaa** [Vikash-8090-Yadav/Future.WebNet#295]
### Project title
Youtube Clone
### Project Description
A simple clone using HTML and CSS
### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? YES

<hr/>

**Comment by harshit-sharmaaa** [comment]
Hey @Vikash-8090-Yadav Please assign me this under SSOC '23

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this.
