### ISSUE TITLE
Rock Paper Scissor Game under SSOC '23

### ISSUE THREAD

**Issue by harshit-sharmaaa** [Vikash-8090-Yadav/Future.WebNet#296]
### Project title
ROCK PAPER SCISSOR GAME
### Project Description
I want to add a rock paper scissor game using HTML CSS and JavaScript

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? Yes

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this.
