### ISSUE TITLE
Music Shop webpage

### ISSUE THREAD

**Issue by Shu12388y** [Vikash-8090-Yadav/Future.WebNet#301]
### Project title
Music Shop webpage

### Project Description
landing page for a music shop

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? yes

@Vikash-8090-Yadav can you assign this issue to me

<hr/>

![musicshop-website](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/c6d2f675-a771-4773-be8c-ff9d25dfecac)

**Comment by MohdSultanGit** [comment]
Hey @Vikash-8090-Yadav Please assign this issue to me as I am really want to work on this issue
