### ISSUE TITLE
Amazon Clone

### ISSUE THREAD

**Issue by TanishqSiva** [Vikash-8090-Yadav/Future.WebNet#308]
Project title
Amazon Clone

Project Description
This is an E-COMMERCE website, tech stack to used is HTML, CSS, Js

Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? Yes
![Amazon clone](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/127381848/3ef2417a-1980-4253-b380-ba30c568a101)
<hr/>

**Comment by TanishqSiva** [comment]
Please @Vikash-8090-Yadav assign this to me so that ill be start working on it, to add an ecommerce clone to our front-end project.

**Comment by TanishqSiva** [comment]
Is anyone intrested to work on this issue to make an add to card interface please tag me.

**Comment by MohdSultanGit** [comment]
Hey , It would be great if i got this issue assigned

**Comment by TanishqSiva** [comment]
> Hey , It would be great if i got this issue assigned

Tag @Vikash-8090-Yadav to assign as how i did. 

Will you make shop cart to this clone

**Comment by MohdSultanGit** [comment]
@Vikash-8090-Yadav Hey, It would be great if i got assigned with this issue.

**Comment by MohdSultanGit** [comment]
@TanishqSiva Yeah I can make shopping cart for this clone .
We can discuss about it on discord here is my discord i'd: Mohd Sultan#9593

**Comment by TanishqSiva** [comment]
> @TanishqSiva Yeah I can make shopping cart for this clone . We can discuss more about this project on discord. Here is my discord i'd: Mohd Sultan#9593

**Comment by MohdSultanGit** [comment]
@TanishqSiva why you cloaed this issue ?

**Comment by MohdSultanGit** [comment]
@Vikash-8090-Yadav which repo should I have to explore can you please be more specific

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav which repo should I have to explore can you please be more specific 

All. Find some good web3 project

**Comment by MohdSultanGit** [comment]
@Vikash-8090-Yadav I want to say that where I can find that repo can you please provide me a link of it please

**Comment by TanishqSiva** [comment]
> @Vikash-8090-Yadav I want to say that where I can find that repo can you please provide me a link of it please
https://github.com/Vikash-8090-Yadav/Future.WebNet
