### ISSUE TITLE
[SSoC 2.0] Music Guessing Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#309]
### Project title
Title - Music Guessing Game

### Project Description
- This game can be played by more than 2 members.
- In this game, a song tune will play which is of around 10 seconds.
- After listening this tune, four options are visible having the name of songs.
- Out of four options, one option having the name of that song and pressed on that option.
- In this way, scoreboard will update.

### Doc Domain

- [x] Other , feel free to mention below
( Only using HTML, CSS, and JS )

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav please assign this task to me for a successful contribution under SSoC 2.0 program

**Comment by MohdSultanGit** [comment]
Hey @Avdhesh-Varshney did you get this issue ?

**Comment by Avdhesh-Varshney** [comment]
> Hey @Avdhesh-Varshney did you get this issue ?

@MohdSultanGit Yes, this issue is assigned to me and i have completed it at mid-night.

**Comment by MohdSultanGit** [comment]
Alright @Avdhesh-Varshney
