### ISSUE TITLE
Netflix Landing Page in Frontend Projects

### ISSUE THREAD

**Issue by dontwike** [Vikash-8090-Yadav/Future.WebNet#310]
Project title:
Title - Netflix Landing Page

Project Description:
Movies, TV shows, and Recently Watched board, which the API Regularly updates.

Tech: ReactJS, Sass.

Are you contributing under any open-source program?
No, SSoC 2.0

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav I'm a SSOC contributer , please assign this to me

**Comment by dontwike** [comment]
Hey Vikash, I have added the Readme.md you can check.
