### ISSUE TITLE
Chatting Web Application

### ISSUE THREAD

**Issue by TanishqSiva** [Vikash-8090-Yadav/Future.WebNet#313]
# Project title
Chatting Web Application

### Project Description
This is a web application like Chatting clone.
Which is also responsive made by (HTML, CSS, Js (vanilla js))

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? Yes
![image](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/127381848/b6596356-b3ae-41c6-b678-cbc3b5b60125)

<hr/>

**Comment by TanishqSiva** [comment]
@Vikash-8090-Yadav Please assign this project to me. so that ill start working on it

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this.
