### ISSUE TITLE
[Ssoc'23 2.0]Correction in Readme.md file

### ISSUE THREAD

**Issue by mswat5** [Vikash-8090-Yadav/Future.WebNet#318]
### Description of  the change
Making some grammatical changes in the readme file (mainly in the About section).

### Domain of Docs
- Readme

#### Are you contributing under any open-source program?
yes, SSoc'23

<hr/>

**Comment by mswat5** [comment]
@Vikash-8090-Yadav can u please assign it to me?

**Comment by Vikash-8090-Yadav** [comment]
Gr8, start working on this.
