### ISSUE TITLE
Clothing shop webPage

### ISSUE THREAD

**Issue by Shu12388y** [Vikash-8090-Yadav/Future.WebNet#342]
### Project title
Clothing shop webPage

### Project Description
(Describe the project over here)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? YES
@Vikash-8090-Yadav  can you assign this issue to me

<hr/>

![Screenshot from 2023-06-19 19-50-47](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/53352c6a-42ec-48ef-b081-3f98ec20952d)

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this
