### ISSUE TITLE
Coffee Shop webpage

### ISSUE THREAD

**Issue by Shu12388y** [Vikash-8090-Yadav/Future.WebNet#343]
### Project title
Coffee Shop webpage

### Project Description
(Describe the project over here)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? Yes

@Vikash-8090-Yadav  can you assign this issue to me

<hr/>

![Screenshot from 2023-06-19 20-00-05](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/a8fb1a3c-72cc-4aad-8a68-07140c0ad01a)

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this
