### ISSUE TITLE
Pet Shop WebPage

### ISSUE THREAD

**Issue by Shu12388y** [Vikash-8090-Yadav/Future.WebNet#344]
### Project title
Pet Shop WebPage

### Project Description
(Describe the project over here)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? Yes

@Vikash-8090-Yadav can you assign the issue to me

<hr/>

![Screenshot from 2023-06-19 19-52-24](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/e35dbbfb-6b5f-45e7-9f1f-3008ba4a9fea)

**Comment by shubhisingh184** [comment]
@Shu12388y Are you contributing under SSOC'23?

**Comment by Shu12388y** [comment]
@shubhisingh184 YES
