### ISSUE TITLE
Donation Webpage

### ISSUE THREAD

**Issue by Shu12388y** [Vikash-8090-Yadav/Future.WebNet#345]
### Project title
Donation Webpage

### Project Description
(Describe the project over here)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ? Yes

@Vikash-8090-Yadav  can you assign this issue to me 

<hr/>

![Screenshot from 2023-06-19 20-01-53](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/91714143/ef971be3-e686-43c3-bdb6-8348ae9d3686)

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this

**Comment by Vikash-8090-Yadav** [comment]
Are u still working on this, if not please close this issue.
