### ISSUE TITLE
Snake game 

### ISSUE THREAD

**Issue by Adityamishra9719** [Vikash-8090-Yadav/Future.WebNet#346]
### Project title
 Snake game 

### Project Description
Hi @Vikash-8090-Yadav , I want to add a snake game . it is very interesting game and it is a web game made using HTML , CSS JAVASCRIPT . 
Please assign it to me .
My branch will be Adityamishra9719

It will look like below image :-
![Screenshot 2023-06-20 200425](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/105539123/05f8eed6-819f-43ea-b258-de0b4cd7c769)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes , in  GSsoc'23 .
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this

**Comment by Adityamishra9719** [comment]
Okk thank you
