### ISSUE TITLE
Personal Portfolio 

### ISSUE THREAD

**Issue by JAYANTH5775** [Vikash-8090-Yadav/Future.WebNet#347]
### Project title
Personal Portfolio Website

### Project Description
It is a personal Portfolio   website of the showcasing the projects , technologies   in which the candidate is good at and the achivements done,   services offered contact details 

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
I'm a SSOC contributor please assign me this issue @Vikash-8090-Yadav  sir :)

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this

**Comment by Manish12-verma** [comment]
Hey please assign this issue to me

**Comment by Vikash-8090-Yadav** [comment]
Are u still working on this, if not please close this issue.
