### ISSUE TITLE
Add Readme for Frontend Projects [SSOC'23]

### ISSUE THREAD

**Issue by harshit-sharmaaa** [Vikash-8090-Yadav/Future.WebNet#348]
I want to add a readme for frontend projects that will give a glimpse of all the projects and a short description

I request @Vikash-8090-Yadav To assign this issue to me under SSOC' 23

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this.

**Comment by Avdhesh-Varshney** [comment]
@shubhisingh184 @Vikash-8090-Yadav can you please assign this issue to me to contribute under SSoC

**Comment by Vikash-8090-Yadav** [comment]
@harshit-sharmaaa are u still working on this?

**Comment by harshit-sharmaaa** [comment]
@Vikash-8090-Yadav please assign this issue to him, as i got busy with my exams currently
