### ISSUE TITLE
Digital Clock

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#355]
### Project title
(Write project title over here)

### Project Description
(Describe the project over here)
I would like to create a Digital clock using Html , Css and Javascript. It will show the time as same as a normal clock.
It would strengthen my skills to used date methods .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 this one is still with no description, and don't raise more than 2 issues at a time. Complete previous one and then raise next one.

**Comment by Tusharjoshi1703** [comment]
Okay ! I'll follow the instructions.

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 assigned to you. Start working on it.

**Comment by Tusharjoshi1703** [comment]
Thank you for assigning it to me

**Comment by MohdSultanGit** [comment]
Hey @Tusharjoshi1703 Can I work on this issue ??
