### ISSUE TITLE
Month Calender

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#356]
### Project title
(Write project title over here)
Month Calender

### Project Description
(Describe the project over here)
I would like to create a Month Calender using Html , Css and Javascript. It will show the date and gets updated daily.
 .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@Tusharjoshi1703  start working on this.

**Comment by Tusharjoshi1703** [comment]
I have completed the project and created PR . Please have a look at it.
