### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#357]
### Project title
(Write project title over here)
Random Password Generator

### Project Description
(Describe the project over here)
I would like to create a Random Password generator using Html , Css and Javascript. It will generate random passwords which users want by clicking the button .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 You should give the proper description about the project and the changes you want to commit, then only we can consider this issue. Hope it helps.

**Comment by Tusharjoshi1703** [comment]
Okay ! Sorry for the inconvenience

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 No worries, give proper description to each of your issue.

**Comment by Tusharjoshi1703** [comment]
Hey ! I have given a proper description to each of my issue . Please review
it and let me know if you assign any issues to me.

Thank You.

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 did you change something after the pr got merged?

**Comment by Tusharjoshi1703** [comment]
No!

**Comment by shubhisingh184** [comment]
Okay.
