### ISSUE TITLE
Random Color Generator

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#358]
### Project title
(Write project title over here)
Random Color Generator
### Project Description
(Describe the project over here)
I would like to create a Random Color Generator using Html , Css and Javascript. It will generate random colors when users clicks on the generate button .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
@Tusharjoshi1703  start workijg on this .

**Comment by Vikash-8090-Yadav** [comment]
Are u still working on this, if not please close this issue.

**Comment by Tusharjoshi1703** [comment]
Yes ,by tomorrow I'll raise the Pr.Sorry for the inconvenience
