### ISSUE TITLE
Image Slider

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#359]
### Project title
(Write project title over here)
Image Slider
### Project Description
(Describe the project over here)
I would like to create an Image Slider using Html , Css and Javascript. The user will be able to use slider of images .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 Are you contributing under any open source program?

**Comment by Tusharjoshi1703** [comment]
Yes ! I have contributed to Future web earlier under SSOC'23
