### ISSUE TITLE
Anime Pic Generator

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#360]
### Project title
(Write project title over here)
Anime Pic Generator

### Project Description
(Describe the project over here)
I would like to create an Anime Pic Generator using Html , Css and Javascript. Here the user can generator Anime Pics when clicked on generate the button .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Tusharjoshi1703** [comment]
Okay 👍 . Thank you for assigning it to me .

**Comment by Vikash-8090-Yadav** [comment]
Are u still working on this, if not please close this issue.

**Comment by Tusharjoshi1703** [comment]
Yes ,by tomorrow I'll raise the Pr.Sorry for the inconvenience
