### ISSUE TITLE
Bmi Calculator

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#361]
### Project title
(Write project title over here)
Bmi Calculator
### Project Description
(Describe the project over here)
I would like to create a Bmi Calculator using Html , Css and Javascript. You can calculate your Bmi as it has user-friendly interface .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 closing this issue, someone else already working on this issue, please search the project topic on "issues" section before raising an issue. So, that you will not face that kind of thing in future.

**Comment by Tusharjoshi1703** [comment]
Okay !
