### ISSUE TITLE
Dad Jokes Generator

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#363]
### Project title
(Write project title over here)
Dad Jokes Generator

### Project Description
(Describe the project over here)
I would like to create a Dad Jokes Generator using Html , Css and Javascript. In this , it will generate random dad jokes and everytime it generates different jokes .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 closing this issue as we do not accept  front-end projects anymore from now on.
