### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#364]
### Project title
(Write project title over here)
Temperature Converter
### Project Description
(Describe the project over here)
I would like to create a Temperatur Converter  using Html , Css and Javascript. It can allow you to convert temperature to various units .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Saloni020** [comment]
@Tusharjoshi1703 Can you assign this project to me?

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 assigned to you. Start working on it.

**Comment by Tusharjoshi1703** [comment]
Thanks for assigning it to me

**Comment by Avdhesh-Varshney** [comment]
@shubhisingh184 @Vikash-8090-Yadav can you please assign this project to me

**Comment by Vikash-8090-Yadav** [comment]
Are u still working on this, if not please close this issue.

**Comment by Tusharjoshi1703** [comment]
Yes ,by tomorrow I'll raise the Pr.Sorry for the inconvenience
