### ISSUE TITLE
Photo Gallery

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#365]
### Project title
(Write project title over here)
Photo Gallery

### Project Description
(Describe the project over here)
I would like to create a Photo Gallery using Html , Css and Javascript. It allows us to make photo gallery by storing our images .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by MohdSultanGit** [comment]
Hey @Tusharjoshi1703 can I work on this issue ??

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 closing this issue as you have raised too many issues. Hope you understand that.
