### ISSUE TITLE
StopWatch

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#367]
### Project title
(Write project title over here)
StopWatch
### Project Description
(Describe the project over here)
I would like to create a StopWatch using Html , Css and Javascript. It allows us to use a stopwatch in seconds and milliseconds .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by shubhisingh184** [comment]
@Tusharjoshi1703 closing this issue as someone else is already working on similar project. Keep coming with good ideas !!
