### ISSUE TITLE
Age calculator

### ISSUE THREAD

**Issue by Tusharjoshi1703** [Vikash-8090-Yadav/Future.WebNet#368]
### Project title
(Write project title over here)
Age Calculator
### Project Description
(Describe the project over here)
I would like to create Age Calculator using Html , Css and Javascript. It will calculate ur age from current date and u have to give some data .Please assign it to me.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by dontwike** [comment]
Can i take this Issue

**Comment by Tusharjoshi1703** [comment]
Sorry bro , but I have started working on it.😊

**Comment by Avdhesh-Varshney** [comment]
@shubhisingh184 @Vikash-8090-Yadav can you please assign this project to me

**Comment by Vikash-8090-Yadav** [comment]
@Tusharjoshi1703 are u working on this?

**Comment by Tusharjoshi1703** [comment]
Yes, due to exams I couldn't complete it.But I'll do it within 2 days.
