### ISSUE TITLE
[SSoC 2.0] Sound Equalizer Project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#369]
### Project title
Title - Sound Equalizer

### Project Description
- A clear and concise description of the project you are going to add to this repository.
- Sound Equalizer will create using HTML, CSS and JS
- This site will be responsive
- Effective animation and lighting effect will attract the users so much
- Just simple model / clone of sound equalizer
- With 3 functionalities like music, mic, and headphone.
- Using slider will show the details of how much decrement or increment is done

### Doc Domain

- [X] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 Open Source Program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir, Please assign this project to me to work on it and contribute under SSoC 2.0 program

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney please specify the doc domain.

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney assigned to you. Start working on it.
