### ISSUE TITLE
[SSoC 2.0] Guess The Gender By The Name

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#370]
### Project title
Title - Guess The Gender By the Name

### Project Description
- Front end project
- Created using HTML, CSS and JS
- Sending request using API key
- Using API key, data will tell the status of gender of the entered name
- Responsive towards the mobile devices
- Responsive User interface with effective color gradients

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 Program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir, please assign this Api based project to me to work on it and give a valuable contribution under SSoC 2.0 open source program

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney assigned to you. Start working on this issue.
