### ISSUE TITLE
[SSOC 2.0] Frontend Project Mi Store Clone

### ISSUE THREAD

**Issue by akshatmishra25** [Vikash-8090-Yadav/Future.WebNet#372]
### Project title
Mi Store Clone

### Project Description
This is a frontend project in which Mi-Store Clone has been made

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
  [SSOC 2.0]
![Screenshot (54)](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/106366272/c3962a68-4cb9-4c1f-8a9f-5d95d6ea37b0)

<hr/>

**Comment by shubhisingh184** [comment]
@akshatmishra25 assigned to you. Start working on it.

**Comment by akshatmishra25** [comment]
> @akshatmishra25 assigned to you. Start working on it.

Thanks @shubhisingh184 
I have made the PR
