### ISSUE TITLE
[SSoC 2.0] Time Watcher Project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#380]
### Project title
(Write project title over here)
Title - Time Watcher
Tech using - HTML, CSS and JS

### Project Description
(Describe the project over here)
- This project will tells the used how much time is going on from any particular date.
- This project has continuously moving clock, even for the milli seconds.
- Continuously moving clock takes exact date and time to calculate how much time has finished till today.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir, please assign this project to me to work on it and give a valuable contribution under SSoC 2.0 program.

**Comment by shubhisingh184** [comment]
Okay @Avdhesh-Varshney ! Start working on it.
