### ISSUE TITLE
[SSoC 2.0] Generate leap years in a range

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#381]
### Project title
Title - Generate Leap years
Tech using - HTML, CSS and JS

### Project Description
(Describe the project over here)
- Front end project
- This project has a attractive and responsive user interface
- Generate number of leap years in between two entered years
- This project will tell the number of leap years and enlist those years
- This project can also check the entered year is a leap year or not

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav Sir, please assign this project to me to give a valuable contribution under SSoC 2.0 program

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney assigned to you!! Start working on it.

**Comment by Saloni020** [comment]
@shubhisingh184 Sir, Can I be please assigned this project?
