### ISSUE TITLE
Updation in Navigation bar of Google Clone

### ISSUE THREAD

**Issue by bugzzz4u** [Vikash-8090-Yadav/Future.WebNet#383]
### Description of  the change
The navigation bar has a different font style and need changes to look exactly like Google page. Addition of different headings like account etc is also needed.
Changes will be done using HTML and CSS
Present :
![image](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/125059410/002010d8-75cc-4c5f-aafd-6bc9eba51da8)

### Domain of Docs

- [] Readme
- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

**Comment by shubhisingh184** [comment]
@bugzzz4u assigned to you. Start working on it.

**Comment by Saloni020** [comment]
@shubhisingh184 Assign this project to me please
