### ISSUE TITLE
Updation in Guess The Gender By Name

### ISSUE THREAD

**Issue by bugzzz4u** [Vikash-8090-Yadav/Future.WebNet#385]
### Description of  the change
The logo and the main heading of the website are aligned in the same line which is giving a bad look to the website. 
Changes needed:
1) Logo and heading would be placed in different rows.
2) Styling of Logo
3) Styling of Heading as too much letter spacing is given.
Additional styling changes will also be made accordingly.

Present:
![image](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/125059410/7735ce16-0906-4e91-b269-bb1b5e22724b)

### Domain of Docs

- [] Readme
- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by shubhisingh184** [comment]
@bugzzz4u assigned to you. Start working on this issue.

**Comment by Saloni020** [comment]
@shubhisingh184 Can this issue be assigned to me?

**Comment by shubhisingh184** [comment]
@Saloni020 this issue is already assigned to someone else, please come up with some new idea and create your own issue. Hope it helps!
