### ISSUE TITLE
Swiggy Clone website

### ISSUE THREAD

**Issue by TanyaNegi10** [Vikash-8090-Yadav/Future.WebNet#386]
### Description of  the change
I want to work on this project ,kindly assign me this

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, in SSOC

**Comment by shubhisingh184** [comment]
@TanyaNegi10 assigned to you. Start working on this project.

**Comment by shubhisingh184** [comment]
@TanyaNegi10 closing this issue, as this project is already present in this repo. Please come up with some new ideas!
