### ISSUE TITLE
Cricket website

### ISSUE THREAD

**Issue by Saloni020** [Vikash-8090-Yadav/Future.WebNet#389]
### Description of  the change
I'd like to improve the UI of the cricket website.

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes to SSOC'23

<hr/>

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav Could you please assign this to me?

**Comment by shubhisingh184** [comment]
@Saloni020 closing this issue as this is already assigned to someone else. Please come up with some new idea and check other issues by searching in issues section before raising a new one
