### ISSUE TITLE
Spotify Clone

### ISSUE THREAD

**Issue by Saloni020** [Vikash-8090-Yadav/Future.WebNet#390]
### Description of  the change
I'd like to work on this project. Please assign it to me

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
YES SSOC'23

<hr/>

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav Could you assign this to me?

**Comment by shubhisingh184** [comment]
@Saloni020 please specify the details of the changes.
