### ISSUE TITLE
Weather app website

### ISSUE THREAD

**Issue by Saloni020** [Vikash-8090-Yadav/Future.WebNet#391]
### Description of  the change
I'd like to work on the weather app project

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
YES SSOC '23

<hr/>

**Comment by Saloni020** [comment]
@Vikash-8090-Yadav Can you assign this to me?

**Comment by shubhisingh184** [comment]
@Saloni020 closing this issue as this project is already present. Please check previous issues and projects before raising next one

**Comment by shubhisingh184** [comment]
Closed
