### ISSUE TITLE
Level0_Send to Ether

### ISSUE THREAD

**Issue by Saloni020** [Vikash-8090-Yadav/Future.WebNet#392]
### Description of  the change
I'd like to make the changes to UI of this project .

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by Saloni020** [comment]
@shubhisingh184 Could you assign me this?

**Comment by shubhisingh184** [comment]
@Saloni020 please give proper details of the changes that you want to do in that project.
