### ISSUE TITLE
[SSoC 2.0] Biography of Mahatma Gandhi - A Freedom Fighter

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#395]
### Project title
(Write project title over here)
Title - Biography of Mahatma Gandhi - A Freedom Fighter
Tech used - HTML, CSS and JS

### Project Description
(Describe the project over here)
- Showing the whole life journey of Mahatma Gandhi
- Using Images visualize in a interesting manner
- Adding heading, bullet points make the webpage a attractive look.

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 please assign this project to me

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney assigned to you. Start working on it.
