### ISSUE TITLE
[SSoC 2.0] Cloning the front-end of ChatGPT website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#396]
### Project title
(Write project title over here)
Title - Clone of ChatGPT
Tech using - HTML, CSS and JS

### Project Description
(Describe the project over here)
- Cloning the website of chatGPT

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 please assign this project to me

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney assigned to you. Start working on it.
