### ISSUE TITLE
PWD Help Website

### ISSUE THREAD

**Issue by NupurHardiya** [Vikash-8090-Yadav/Future.WebNet#398]
Project title :-  PWD Help Website

Project Description :-

This website is designed to help people with disabilities find information and resources about opportunities and facilities available to them. The website includes a variety of sections, including:

Opportunities :- This section provides information about government and non-government programs and organizations that offer opportunities for people with disabilities, such as job training, education, and housing.

Facilities :- This section provides information about disability-friendly facilities, such as hotels, restaurants, and transportation options.

Schools :- This section provides information about special schools for people with disabilities.

Contact us :- This section provides contact information for the website administrators.

Doc Domain

- [✅] Solidity , Html, CSS , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
yes . ssoc'23
<hr/>

**Comment by NupurHardiya** [comment]
Dear SSOC'23 organizers @Vikash-8090-Yadav,
I kindly request to be assigned the task of developing a section on the PWD Help website that provides information about opportunities and facilities available to people with disabilities. I can do this using HTML, CSS, and JavaScript.

I am confident that I can create a section that is informative, accessible, and user-friendly. I am eager to contribute to this important project, and I look forward to hearing from you soon.

Thanks!

**Comment by shubhisingh184** [comment]
@NupurHardiya assigned to you. Start working on it.
