### ISSUE TITLE
Digital Clock 

### ISSUE THREAD

**Issue by Adityamishra9719** [Vikash-8090-Yadav/Future.WebNet#399]
### Project title
Digital clock

### Project Description
It is a Digital clock made using HTML , CSS AND JAVASCRIPT.
The clock will look like the below screen shot :-

![Screenshot 2023-07-02 190826](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/105539123/934d6f95-5c66-490f-833c-56bcad5bf93f)
 
Pls assign this to me .
my branch will be Adityamishra9719.

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
yes 
<hr/>

**Comment by shubhisingh184** [comment]
@Adityamishra9719 closing this issue, as someone else is working on this issue.
