### ISSUE TITLE
A NOTES KEEPING SITE (MAGIC NOTES ) 

### ISSUE THREAD

**Issue by Adityamishra9719** [Vikash-8090-Yadav/Future.WebNet#400]
### Project title
MAGIC NOTES

### Project Description
It is a simple notes keeping project .
It is a REACT APP .
There are two fields the title field and the message field and a add button using it you can add the note
There is delete button for deleting the notes.
It looks like the below screen shot :-

## **Screenshots**
![Screenshot 2023-07-02 204239](https://github.com/TusharKesarwani/Front-End-Projects/assets/105539123/0f887681-caba-47b9-9a04-64982fe29c04)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [X] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
YES
<hr/>

**Comment by shubhisingh184** [comment]
@Adityamishra9719 assigned to you. Start working on it.
