### ISSUE TITLE
Bucket_list

### ISSUE THREAD

**Issue by TanyaNegi10** [Vikash-8090-Yadav/Future.WebNet#401]
### Description of  the change
I want to work on this project. It is a frontend project using html and css where people can see the things they want to do and places  they want to explore. kindly assign me this.

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

yes,I'm contributing under ssoc

**Comment by shubhisingh184** [comment]
@TanyaNegi10 assigned to you. Start working on it.

**Comment by TanyaNegi10** [comment]
@shubhisingh184 I just complete the new project of bucketlist but I raised this issue through improve my file so now what should I do or where should I upload this project

**Comment by TanyaNegi10** [comment]
Here are some ss of my project

![Bucketpage1](https://github.com/TanyaNegi10/Bizwizz/assets/131293785/3914a1bd-d983-403c-bbe7-aacb28cb83af)

![Bucketpage2](https://github.com/TanyaNegi10/Bizwizz/assets/131293785/3624bba8-ab86-4e84-b5ce-ef4003a9765d)

**Comment by shubhisingh184** [comment]
@TanyaNegi10 now after completing your project, you have to create a pull request from your end, when that pull request gets merged, your contribution of this project will get done at that point.
