### ISSUE TITLE
[SSoC 2.0] Large Factorial Generator Project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#403]
### Project title
(Write project title over here)
Title - Factorial Calculator
Tech using - HTML, CSS and JS

### Project Description
(Describe the project over here)
- Front-end Project
- Card and colouring effect to attract users
- Animated effects
- Enter the number, project will return the factorial of that entered number instantly

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 please assign this task to me

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 please assign this task to me. I have done with this project

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney assigned to you. Please don't start working on your issue until you get assigned. Okay!
