### ISSUE TITLE
To add a Ping Pong game 

### ISSUE THREAD

**Issue by ayan-joshi** [Vikash-8090-Yadav/Future.WebNet#406]
### Project title
Ping Pong Multiplayer game 

### Project Description
Ping pong, also known as table tennis, is a sport in which two or four players hit a lightweight ball back and forth across a table using small solid rackets.
They must prevent the ball from touching the surface of the table on their side
How to play? 🕹️
Controls:
W: Up / S: Down (Player 1)
↑: Up / ↓: Down (Player 2)
Players must allow a ball played towards them to bounce once on their side of the table and must return it so that it bounces on the opposite side.
A point is scored when a player fails to return the ball within the rules. A player or team wins a game by scoring 11 points with a two-point margin.
This is a endless game, so both players can play as much as they want
Also added the Pause , Resume and Reset button below to make it more interesting.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
I'm a SSOC contributor , please assign me this issue @Vikash-8090-Yadav 
<hr/>

**Comment by shubhisingh184** [comment]
@ayan-joshi assigned to you. Start working on it.
