### ISSUE TITLE
Want to add one more project idea 

### ISSUE THREAD

**Issue by anshulsoni4** [Vikash-8090-Yadav/Future.WebNet#416]
We are trying to build a web3 marketplace where the users can buy some assets such as ebooks, pdfs, and other similar kind of files from the creators who want to make some bucks by selling their work.

**Comment by shubhisingh184** [comment]
@anshulsoni4 Are you working in a team or is it an individual contribution? Just confirming as you wrote "we". Let me know, okay!

**Comment by anshulsoni4** [comment]
> @anshulsoni4 Are you working in a team or is it an individual contribution? Just confirming as you wrote "we". Let me know, okay!

oh, my bad
working individually

**Comment by shubhisingh184** [comment]
Okay, no worries.

**Comment by shubhisingh184** [comment]
@anshulsoni4 assigned to you. Start working on it.

**Comment by anshulsoni4** [comment]
sure thanks

**Comment by anshulsoni4** [comment]
@shubhisingh184 i have raised a PR please check
