### ISSUE TITLE
To add Countdown Timer

### ISSUE THREAD

**Issue by yashhibare7** [Vikash-8090-Yadav/Future.WebNet#420]
### Project title
Countdown Timer

### Project Description
Countdown Timer

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

<hr/>

**Comment by shubhisingh184** [comment]
@yashhibare7 closing this issue as similar project is already present in the repository.
