### ISSUE TITLE
Memory Game

### ISSUE THREAD

**Issue by Vyshnavi21504** [Vikash-8090-Yadav/Future.WebNet#421]
### Project title
Memory Game

### Project Description
It typically involves a set of cards or tiles with matching pairs that are initially placed face down. The objective is to flip over two cards at a time and remember their positions. If the cards match, they stay face up. If they don't match, they are flipped back face down, and you continue trying to find matching pairs. The game continues until all pairs are successfully matched. 

### Doc Domain

- [X] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
yes , Under SSOC
<hr/>

**Comment by shubhisingh184** [comment]
@Vyshnavi21504 assigned to you. Start working on it.

**Comment by Vyshnavi21504** [comment]
I have completed the issue .pls check it and merge it @shubhisingh184
