### ISSUE TITLE
Archery game 

### ISSUE THREAD

**Issue by Vyshnavi21504** [Vikash-8090-Yadav/Future.WebNet#422]
### Project title
Archery game 

### Project Description
The archery game is a simple game where the player shoots arrows at a moving target. The target moves horizontally across the screen, and the player's goal is to hit the target as many times as possible .

### Doc Domain

- [X] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes , under [SSOC 2.0]

![archeryss](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/111994644/d42b6e62-c72c-4e17-9661-f9143864b658)
<hr/>

**Comment by shubhisingh184** [comment]
@Vyshnavi21504 assigned to you. Start working on it and do follow the guidelines of creating a pull request.

**Comment by Vyshnavi21504** [comment]
I have completed the issue. pls check it and merge it @shubhisingh184
