### ISSUE TITLE
To add a Dice Game

### ISSUE THREAD

**Issue by ayan-joshi** [Vikash-8090-Yadav/Future.WebNet#425]
### Project title
Lucky Die

### Project Description
Childhood memories of dice games. Play once to check how lucky you are. A simple multiplayer game. 
Rules : 
* 2 player game.
* If the  player gets 1 in dice then he lose his chance
* the dice value will be added to the current score every time you role the die.
* Then  Hold is used to hold your current score and add it to Total Score
* If the total score is 100 or more  then U are the winner 

Concepts : 
* HTML  
* CSS
* JavaScript

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
I'm a SSOC contributor , please assign me this issue @shubhisingh184 @Vikash-8090-Yadav 
<hr/>

**Comment by shubhisingh184** [comment]
@ayan-joshi assigned to you. Start working on it.
