### ISSUE TITLE
[SSoC 2.0] FAQ website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#427]
### Project title - FAQ Website 
(Write project title over here)

### Project Description
(Describe the project over here)
- This website show the question and answer.
- This website has box effect for each question with ease open and close.
- Responsive towards the small devices.

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 please assign this task to me

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney assigned to you. Start working on it.
