### ISSUE TITLE
Maths for Kids 

### ISSUE THREAD

**Issue by MohdSultanGit** [Vikash-8090-Yadav/Future.WebNet#428]
### Project title
Maths for kids

### Project Description
With this website kids can learn maths easily. From this project they learn Addition, Subtraction, Multiplication and subtraction with easy steps

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
![Screenshot (250)](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/132590302/2b2b2768-ef3c-4ab1-8c69-88e21ec9b158)

<hr/>

**Comment by shubhisingh184** [comment]
@MohdSultanGit assigned to you. Start working on it.
