### ISSUE TITLE
[SSoC 2.0] Music Studio Game

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#435]
### Project title
Title - Music Studio Game
Tech using - HTML, CSS and JS

### Project Description
- Creating a Music Studio game.
- with 6 different sounds.
- with cards effect on the buttons.
- Adding day and night mode toggle button also.
- Attractiver user interface with best experience.
- responsive towards the mobile devices.

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 please assign this task to me

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney Can you please elaborate more about how does it works, specially how can anyone play this game?

**Comment by Avdhesh-Varshney** [comment]
![image](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/114330097/cde3e943-29ed-4b39-b311-2f73aa496fe6)

@shubhisingh184 @Vikash-8090-Yadav Game looks like this just press the buttons and enjoy the instument sounds

Please assign it to me. I am ready with this project and want to create a pull request under SSoC 2.0 program
