### ISSUE TITLE
Doodle Jump Game

### ISSUE THREAD

**Issue by Vyshnavi21504** [Vikash-8090-Yadav/Future.WebNet#438]
### Project title
Doodle Jump

### Project Description
In Doodle Jump, you control a character called "The Doodler," who is a small, four-legged creature . The goal of the game is to guide the Doodler as high as possible by jumping on platforms .

### Doc Domain

- [X] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
SSOC 
<hr/>

**Comment by shubhisingh184** [comment]
@Vyshnavi21504 assigned to you. Start working on it.
