### ISSUE TITLE
Guess the Number

### ISSUE THREAD

**Issue by NupurHardiya** [Vikash-8090-Yadav/Future.WebNet#440]
### Project Description:-

This project is a simple guessing game that allows users to guess a number between 1 and 100. The user enters their guess and the code will tell them if they guessed correctly or incorrectly.

### Doc Domain:-

- [✅] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
YES, SSOC'23

**Comment by NupurHardiya** [comment]
@Vikash-8090-Yadav Please assign this issue to me under SSOC'23

**Comment by shubhisingh184** [comment]
@NupurHardiya Can you please elaborate more about this project? Is it just random guessing or some question related guessing?

**Comment by NupurHardiya** [comment]
@shubhisingh184 
This game is about guessing a number. The game will generate a random number between 1 and 100. The user has to guess the number and submit it to the game. Then, the game will reveal the generated number and indicate whether the user's guess is correct or not.

**Comment by shubhisingh184** [comment]
@NupurHardiya assigned to you. Start working on it.
