### ISSUE TITLE
[SSoC 2.0] GYM Responsive Website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#441]
### Project Description
- Showing effects of cards
- Responsive for the small devices.
- Creative and professional look with best attractive user interface
- Adding animations
- Creating a FAQ section
- Adding a feedback form, etc.

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 sir, please assign this to me so to start working on it

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney assigned to you. Start working on it.
