### ISSUE TITLE
Temperature Converter

### ISSUE THREAD

**Issue by NupurHardiya** [Vikash-8090-Yadav/Future.WebNet#452]
### Project Description:-

_This project is a simple temperature converter that allows users to convert between Celsius and Fahrenheit. The project is written in HTML, CSS, and JavaScript. It uses the following formula to convert between Celsius and Fahrenheit:_

```
fahrenheit = (celsius * 9) / 5 + 32
celsius = ((fahrenheit - 32) * 5) / 9
```
The project also uses HTML and CSS to create a simple user interface. The user interface includes two input fields, one for Celsius and one for Fahrenheit. When the user clicks the "Convert" button, the code converts the value in the Celsius input field to Fahrenheit and displays it in the Fahrenheit input field. If the user has entered a value in the Fahrenheit input field, the code converts the value to Celsius and displays it in the Celsius input field.

### Doc Domain

- [✅] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
YES, SSOC'23.
<hr/>

**Comment by NupurHardiya** [comment]
Hey! @Vikash-8090-Yadav @shubhisingh184 
Please assign this issue to me under SSOC'23

**Comment by shubhisingh184** [comment]
@NupurHardiya closing this issue as someone is already working on this issue. Please come back to us with some new ideas.
