### ISSUE TITLE
Netflix Website Clone

### ISSUE THREAD

**Issue by NupurHardiya** [Vikash-8090-Yadav/Future.WebNet#453]
### Project Description:-

This project is a clone of the Netflix website. It is built using HTML, CSS. The project includes the following features:

A homepage with a search bar and a call to action button to sign up for a free trial.
A section about Netflix Originals.
A section with frequently asked questions.
A footer with links to important pages on the website.

### Doc Domain

- [✅] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
yes , SSOC'23
<hr/>

**Comment by NupurHardiya** [comment]
Hey! @Vikash-8090-Yadav @shubhisingh184 
Please assign this task to me under ssoc'23.

**Comment by shubhisingh184** [comment]
@NupurHardiya assigned to you. Start working on it.
