### ISSUE TITLE
[SSoC 2.0] Design Facebook Logo

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#460]
### Project Description
using HTML, and CSS only
adding neon light effect with dark and light mode effect
also adding hovering effect on logo

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 sir, please assign this task to me

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney don't raise too many issues at the same time.

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney closing this issue as you have already raised a similar kind of issue.
