### ISSUE TITLE
Wants to add a Weather Web App 

### ISSUE THREAD

**Issue by Adityamishra9719** [Vikash-8090-Yadav/Future.WebNet#467]
### Project title
WEATHER WEB APP

### Project Description
This weather web app is made using HTML , CSS , and JAVASCRIPT
It include a search button you can search any city for weather check .
It include a random Background change as per city name .

It looks like :- 
![Screenshot 2023-07-15 175304](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/105539123/81747c61-8f04-469e-b775-60c7e2961c08)

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
 Yes

<hr/>

**Comment by shubhisingh184** [comment]
@Adityamishra9719 closing this issue as we can't accept any front-end projects anymore. Hope you understand!
