### ISSUE TITLE
Full Stack Notes App

### ISSUE THREAD

**Issue by dontwike** [Vikash-8090-Yadav/Future.WebNet#468]
### Project title
Notes App

### Project Description
A Notes taking app where you can manage all of your notes.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below
- [] Spring Boot, Hibernate

#### Are you contributing under any open-source program ?
Yes
<hr/>

**Comment by shubhisingh184** [comment]
@dontwike closing this issue as we can't accept front-end projects anymore. Hope you'll understand!
