### ISSUE TITLE
Delete DS_Store file 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/Future.WebNet#473]
This issue is based on FCFS 

Delete DS_Store file present in the root directory of this repo.

**Comment by sumit851** [comment]
plz add  deatils what to do and assign me as a ssoc 2023 contributor.

**Comment by Vikash-8090-Yadav** [comment]
> plz add  deatils what to do and assign me as a ssoc 2023 contributor.

I already mentioned details in this issue. Please chl once.
