### ISSUE TITLE
Flappy Dragon Game (Python game )

### ISSUE THREAD

**Issue by Adityamishra9719** [Vikash-8090-Yadav/Future.WebNet#487]
### Project title
 Flappy Dragon Game 

### Project Description
I want to add a python project name Flappy Dragon .
It is made using pygame ,random and sys.

### Screen shots
![Screenshot 2023-07-22 151453](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/105539123/fbb75d4d-4cc3-43be-b077-3d94efdc7e2f)

![Screenshot 2023-07-22 145226](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/105539123/429f8058-b610-4544-8c48-082f419c1281)

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [X] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes
<hr/>

**Comment by shubhisingh184** [comment]
@Adityamishra9719 Great! start working on this issue.
