### ISSUE TITLE
[SSoC 2.0] Creating website for this Repository

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#489]
### Project title
(Write project title over here)
Title - Creating website
Tech using - ReactJS

### Project Description
(Describe the project over here)
- Enlist all the contributor's projects
- Showcase the all the contributors
- Adding animations on all the objects
- Creating a json file to add the further projects contributed by contributors

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [x] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@shubhisingh184 @Vikash-8090-Yadav sir, can you please assign this project to me. I will create pr within 1 day to contribute under SSoC 2.0

**Comment by shubhisingh184** [comment]
@Avdhesh-Varshney assigned to you.

**Comment by Vikash-8090-Yadav** [comment]
Hey sorry but we are not accepting the project  for the frontend directory. Thanks!
