### ISSUE TITLE
[SSoC 2.0] Dictionary Application

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Vikash-8090-Yadav/Future.WebNet#500]
### Project Description
- Meaning fetching from API key.
- Displaying the meaning to the user.
- Having best UI and responsiveness to the project.

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Yes, SSoC 2.0 program
<hr/>

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 sir, please assign this project to me

**Comment by Vikash-8090-Yadav** [comment]
Give more details about this project.

**Comment by Avdhesh-Varshney** [comment]
> Give more details about this project.

![image](https://github.com/Vikash-8090-Yadav/Future.WebNet/assets/114330097/5e388235-5b63-4961-a46b-ec03bd86d86b)

<br>

@shubhisingh184 @Vikash-8090-Yadav sir, Looks like this

**Comment by Avdhesh-Varshney** [comment]
@Vikash-8090-Yadav @shubhisingh184 sir, please assign it to me to raise the pull request
