### ISSUE TITLE
Unlocked pragma version in smart contracts.

### ISSUE THREAD

**Issue by AVI-SHUKLA1110** [Vikash-8090-Yadav/Future.WebNet#501]
### Description of  the change
Unlocked Pragma version in multiple contracts.
(Contracts should be deployed using the same compiler version/flags with which they have been tested.

Locking the pragma (for e.g. by not using ^ in pragma solidity 0.5.10) ensures that contracts do not accidentally get deployed using an older compiler version with unfixed bugs.)

Note - it is not a secure practice while writing contracts.

### Domain of Docs
solidity smart contracts

#### Are you contributing under any open-source program ?
No if i get the chance here ,it will be my first

### Resources 
>https://consensys.github.io/smart-contract-best-practices/development-recommendations/solidity-specific/locking-pragmas/
>https://medium.com/the-capital/security-considerations-while-developing-ethereum-smart-contracts-in-solidity-aed8970341c3

**Comment by AVI-SHUKLA1110** [comment]
@Vikash-8090-Yadav  @shubhisingh184  please have a look at this .

**Comment by Vikash-8090-Yadav** [comment]
@AVI-SHUKLA1110  what do want to do? blogs or some projects on this?

**Comment by AVI-SHUKLA1110** [comment]
It's a security recommendation to be implemented across all the smart contracts in ur repos, which might be useful to save the deployment errors due to different pragma versions

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this . and one more thing are u participating in any open source programme like SSOC ?

**Comment by AVI-SHUKLA1110** [comment]
@Vikash-8090-Yadav NO I'm  not , But i want to . Can you guide me
