### ISSUE TITLE
Update TaskContract.sol

### ISSUE THREAD

**Issue by AVI-SHUKLA1110** [Vikash-8090-Yadav/Future.WebNet#503]
### Bound Check for array input.
In the getMyTasks function, there is no bounds checking when copying tasks into the temporary array. If the counter exceeds the temporary array's length, it could lead to an exception. We can add a check to ensure counter doesn't exceed temporary's length.
file path : [Level1/Check-it/backend/contracts/TaskContract.sol](https://github.com/Vikash-8090-Yadav/Future.WebNet/blob/c8419f9227fa70bfbcea4d35060c8d435a9d94d7/Level1/Check-it/backend/contracts/TaskContract.sol)

### Domain of Docs

- [] Readme
- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
No , but i would love to join one.
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Hey sorry but we are not accepting the new issue now. Hope to see the contribution after the programme as well. Thanks!
Feel free to open this.

**Comment by AVI-SHUKLA1110** [comment]
@i already did the required changes and created a pull request ,please merge it
