### ISSUE TITLE
[SSOC'23] Update in README markdown file required

### ISSUE THREAD

**Issue by hustler0109** [Vikash-8090-Yadav/Future.WebNet#504]
Some of the loopholes I have figured out in the README file of the project that needs to be updated:

Missing Introduction: The README starts abruptly with "About Web3.O.World" without providing a clear introduction to the project. It would be better to start with a brief introduction, stating the purpose and goals of the project.

Inconsistent Terminology: The README uses "Web3.O.World" and "Web3" interchangeably, which can be confusing. It would be better to stick to one consistent term throughout the document.

Lack of Project Information: The README doesn't provide enough information about the project itself. It's unclear what the project aims to achieve, what problems it addresses, or its scope.

Unclear Project Structure: While it mentions the inclusion of backend smart contracts and frontend sections, there is no clear explanation of the project's structure or how these components fit together.

Lack of Contribution Guidelines: Although the "How to Contribute" section is provided, it could be more detailed. It's missing essential information, such as coding style guidelines, testing practices, and how issues should be labeled.

Incorrect Dependency Installation: The "How to Setup Locally" section includes the step "npm install node," which is not a valid command. It should be either "npm install" or "npm install node."

Missing License Information: The README does not mention anything about the project's license, which is an essential aspect of open-source projects.

Unclear Contribution Process: The contribution process lacks clarity on how contributions will be reviewed and merged. Adding information about the review process and the roles of maintainers would be helpful.

Formatting and Consistency: Some parts of the README are not well-formatted, such as the "How to make a Pull Request" section, where some steps are not properly indented.

Missing Links: The README mentions links to the blog, tutorials, and repositories but doesn't include the actual URLs. The links should be included for easy access.

Code of Conduct: There is no mention of a code of conduct, which is important for creating a welcoming and inclusive community.

Please assign this issue to me under SSOC'23

**Comment by Vikash-8090-Yadav** [comment]
Hey sorry but we are not accepting the new issue now. Hope to see the contribution after  the programme as well. Thanks!
Feel free to open this.
