### ISSUE TITLE
How to be part of any open source like ssoc.

### ISSUE THREAD

**Issue by AVI-SHUKLA1110** [Vikash-8090-Yadav/Future.WebNet#506]
i want to be part of an ooen source program like ssoc, those who have any knowledge about that please guide me:)

**Comment by Vikash-8090-Yadav** [comment]
Hey thanks for this wonderful query. There any many paid and unpaid open source programme.

Paid: 
GsOC,Outreachy, Lfx, Xros, GSOD, Summer of Bitcoin and many more. 

Unpaid. 

Ssoc, GSSOC, KHARAGPUR WINTER OF CODE, OSS, HACKTOBERFEST and many more.


Now ssoc is over and around NOV SWOC AND GWOC will open



For ssoc and SWOC follow their linkedin page connect with me on linkedin. You can also Check Hack2skill website for SSOC 
AND same follows for the GSSOC AND MANY OTHER PROGRAMME. 

Let me know if u have any other  doubt.

**Comment by AVI-SHUKLA1110** [comment]
thnks for this
