### ISSUE TITLE
To improve Study Material 

### ISSUE THREAD

**Issue by ayan-joshi** [Vikash-8090-Yadav/Future.WebNet#508]
### Description of  the change
I would like to add I would like to add different cheatsheet related to web3 and other frontend languages which can help the contributors as well as the people interacting with the future webnet repository.

### Domain of Docs

- [] Readme
- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
Please assign me this issue under hacktoberfest label @Vikash-8090-Yadav 
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great start working  on this.

**Comment by ayan-joshi** [comment]
@Vikash-8090-Yadav Can you please add the hacktoberfest label
