### ISSUE TITLE
To improve the BlockchainAndWeb3 blog's structure and formatting.

### ISSUE THREAD

**Issue by anushatomar13** [Vikash-8090-Yadav/Future.WebNet#514]
### Description of  the change
I would like to improve the structure of the Blockchain and Web3 blog by adding subheadings, bullet points, highlighting important points, etc. Please assign me this issue @Vikash-8090-Yadav 

<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Great. start working on this.
