### ISSUE TITLE
Add Job Finding Website

### ISSUE THREAD

**Issue by apu52** [Vikash-8090-Yadav/Future.WebNet#522]
### Project title
(Write project title over here)

Job Finding Website

### Project Description
(Describe the project over here)
Hello Sir,
I want to add my project as job finding website.
This repo includes 
- Job Search
- Internship Listings
- Company Profiles
- Performance Tracking
- Bookmarks and Notifications
- User Accounts
- Mobile Responsiveness

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?

I am Participating in **OSEN(Collab-code carnival)**
<hr/>

**Comment by apu52** [comment]
@shubhisingh184 @Vikash-8090-Yadav Please assign me this issue

**Comment by Vikash-8090-Yadav** [comment]
Start working on this
