### ISSUE TITLE
Food Website

### ISSUE THREAD

**Issue by apu52** [Vikash-8090-Yadav/Future.WebNet#523]
### Project title
(Write project title over here)
Food Website

### Project Description
(Describe the project over here)

Hello Sir/ma'am,
I want to add my new Food website project in this repo.
This project includes contains my project on my Food Website😋. I have made it using HTML,CSS & JS. It contains a menu card of different cuisines such as Biriyani , Chinese, Paneer Mania, Veg as well as South Indian.🍕 .

### Doc Domain

- [x] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
I am participating in **OSEN(Collab-code-carnival)**
<hr/>

**Comment by apu52** [comment]
@shubhisingh184 @Vikash-8090-Yadav Please assign me this issue

**Comment by Vikash-8090-Yadav** [comment]
Start working on this
