### ISSUE TITLE
Want to Improve the UI of Web3.0-World/Level2/MetaNft_Minting/

### ISSUE THREAD

**Issue by suraj-git07** [Vikash-8090-Yadav/Future.WebNet#75]
Change the threejs platform overall look to look better and also the form UI

**Comment by Vikash-8090-Yadav** [comment]
@suraj-git07 Great idea .Start working on this .

**Comment by Vikash-8090-Yadav** [comment]
@suraj-git07 Are us till working on this ?

**Comment by 0xSaksham** [comment]
Hey, is somebody working on this?

If not then I can sure do.

**Comment by Parthmandale** [comment]
@Vikash-8090-Yadav ser I can on this issue and make it better, Please assign me this issue.
